language: go

go:
- 1.9

env:
  global:
    - GOSNMP_TARGET=127.0.0.1
    - GOSNMP_PORT=161
  matrix:
    - TRAVIS_GOARCH=amd64 GOOS=linux
    - TRAVIS_GOARCH=386   GOOS=linux
    - TRAVIS_GOARCH=amd64 GOOS=windows
    - TRAVIS_GOARCH=386   GOOS=windows

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install snmpd
 - export GOARCH=$TRAVIS_GOARCH # https://github.com/travis-ci/travis-ci/issues/6126
 - go env # for debugging

install:
 - go get github.com/soniah/gosnmp
 - sudo ./snmp_users.sh
 - sudo /etc/init.d/snmpd restart

script:
 - go test
